/**
 * \file
 * \brief Embeded font `builtin` of size `15` 
 * \note This file is automatically generated by `tool/mkfont`
 */

#ifndef GLCVS_EMBEDED_FONT_BUILTIN15
#define GLCVS_EMBEDED_FONT_BUILTIN15

#include "glcvs/font.h"

/// Embeded builtin font
const glcvs_embeded_font glcvs_embeded_font_builtin_15();

#endif // GLCVS_EMBEDED_FONT_BUILTIN15
