/**
 * \file
 * \brief Embeded font `builtin` of size `13` 
 * \note This file is automatically generated by `tool/mkfont`
 */

#ifndef GLCVS_EMBEDED_FONT_BUILTIN13
#define GLCVS_EMBEDED_FONT_BUILTIN13

#include "glcvs/font.h"

/// Embeded builtin font
const glcvs_embeded_font glcvs_embeded_font_builtin_13();

#endif // GLCVS_EMBEDED_FONT_BUILTIN13
